stages:
  - build
  - test

build-job:
  stage: build
  script:
    - echo "Build stage -> compile all code and build an executable"
    - make

test-job:
  stage: test
  script:
    - echo "Test stage -> run the test cases"
    - make
    - build/stack_test
