name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:      
    - name: build
      run: make
       
    - name: test
      run: ./build/stack_test
      
      
